name: Boom

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: "*/6 * * * *"

jobs:
  boooooom:
    name: Boooooom
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 1
    - name: Install Dependencies
      run: |
          git config --global user.email "3356136957@qq.com"
          git config --global user.name "HelloTools-Bot"
          ip=$(curl -s https://api.ip.sb/ip -A Mozilla)
          for loop in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
          do
            echo $loop_$RANDOM+$ip > god
            echo "第 $loop 次提交"
            git add .
            git commit -m "fox: Update [skip ci]"
          done
          echo LAST_$RANDOM+$ip > god
          
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'fox: Update god0 [skip ci]'
        branch: master
        commit_user_name: HelloTools-Bot
        commit_user_email: 3356136957@qq.com
        commit_author: HelloTools-Bot <3356136957@qq.com>
